version: '3.7'

services:
  app:
    container_name: sdv-rshiny-project-template
    image: sdv-rshiny-project-template
    build:
      context: ..
      dockerfile: docker/Dockerfile.prod
    ports:
      - "8001:80"
