version: '3.7'

services:
  app:
    container_name: dockery-dev
    image: dockery-dev
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    ports:
      - "8888:80"
    volumes:
      - ../app:/app
    environment:
      - HEADER=Sylvans header
