version: '3.7'

services:
  app:
    container_name: dockery
    image: dockery
    build:
      context: ..
      dockerfile: docker/Dockerfile.prod
    ports:
      - "8001:80"
    environment:
      - HEADER=Sylvans header
