version: '3.7'

services:
  app:
    container_name: sdv-rshiny-project-template-dev
    image: sdv-rshiny-project-template-dev
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    ports:
      - "8888:80"
    volumes:
      - ../app:/app
